"joint_angle":
  "arg": [['sh_qOut'], ['ic_q'], ['abc_q'], ['st_q'], ['RobotHardware0_q']]
  "func": ['lambda x, idx, mabiki: [math.degrees(y) for y in x[0][:, idx][::mabiki]]','self.func_codes[0]','self.func_codes[0]','self.func_codes[0]', 'self.func_codes[0]']
  # "field": [[0,1,2,3,4,5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]]
  "field": [[0,1,2,3,4,5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28]]
  # "field": [[0,1,2,3,4,5], [6,7,8,9,10,11], [12,13,14,15,16], [17, 18, 19, 20, 21, 22, 23, 24], [25, 26, 27, 28, 29, 30, 31, 32]]

"right_foot_force":
  "arg": [['sh_rfsensorOut'], ['RobotHardware0_rfsensor'], ['rmfo_off_rfsensor']]
  "field": [[0,1,2,3,4,5]]

"left_foot_force":
  "arg": [['sh_lfsensorOut'], ['RobotHardware0_lfsensor'], ['rmfo_off_lfsensor']]
  "field": [[0,1,2,3,4,5]]

"right_hand_force":
  "arg": [['sh_rhsensorOut'], ['RobotHardware0_rhsensor'], ['rmfo_off_rhsensor']]
  "field": [[0,1,2,3,4,5]]

"left_hand_force":
  "arg": [['sh_lhsensorOut'], ['RobotHardware0_lhsensor'], ['rmfo_off_lhsensor']]
  "field": [[0,1,2,3,4,5]]

"attitude":
  "arg": [['sh_baseRpyOut'], ['st_actBaseRpy'], ['st_currentBaseRpy'], ['kf_rpy']]
  "func": ['lambda x, idx, mabiki: [math.degrees(y) for y in x[0][:, idx][::mabiki]]','self.func_codes[0]','self.func_codes[0]','self.func_codes[0]']
  "field": [[0,1,2]]

"imu":
  "arg": [['RobotHardware0_gsensor'], ['RobotHardware0_gyrometer']]
  "field": [[0,1,2]]

# "torque":
#   "arg": [['RobotHardware0_tau']]
#   "field": [[0,1,2,3,4,5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]]

"tracking":
  "arg": [['st_q','RobotHardware0_q'], ['RobotHardware0_servoState']]
  "func": ['lambda x, idx, mabiki: [math.degrees(y) for y in x[0][:, idx][::mabiki] - x[1][:, idx][::mabiki]]', 'lambda x, idx, mabiki, urata_len=13: [math.degrees(y) for y in x[0][:, (urata_len+1) * idx + (6+1)][::mabiki]]']
  "name": ['st_q-rh_q', 'abc-enc']
  "field": [[0,1,2,3,4,5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28]]
  # "field": [[0,1,2,3,4,5], [6,7,8,9,10,11], [12,13,14,15,16], [17, 18, 19, 20, 21, 22, 23, 24], [25, 26, 27, 28, 29, 30, 31, 32]]

# "joint_velocity":
#   "arg": [['RobotHardware0_dq']]
#   "func": ['lambda x, idx, mabiki: [math.degrees(y) for y in x[0][:, idx][::mabiki]]']
#   "field": [[0,1,2,3,4,5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]]

# "watt":
#   "arg": [['RobotHardware0_tau', 'RobotHardware0_dq']]
#   "func": ['lambda x, idx, mabiki: [math.degrees(y) for y in x[0][:, idx][::mabiki] * x[1][:, idx][::mabiki]]']
#   "field": [[0,1,2,3,4,5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]]


# "12V":
#   "arg": [['RobotHardware0_servoState']]
#   "func": ['lambda x, idx, mabiki, urata_len=13: x[0][:, (urata_len+1) * idx + (9+1)][::mabiki]']
#   # "field": [[0,1,2,3,4,5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]] 
#   "field": [[0,1,2,3,4,5], [6,7,8,9,10,11], [12,13,14,15,16], [17, 18, 19, 20, 21, 22, 23, 24], [25, 26, 27, 28, 29, 30, 31, 32]]

"80V":
  "arg": [['RobotHardware0_servoState']]
  "func": ['lambda x, idx, mabiki, urata_len=13: x[0][:, (urata_len+1) * idx + (2+1)][::mabiki]']
  "field": [[0,1,2,3,4,5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28]]
  # "field": [[0,1,2,3,4,5], [6,7,8,9,10,11], [12,13,14,15,16], [17, 18, 19, 20, 21, 22, 23, 24], [25, 26, 27, 28, 29, 30, 31, 32]]

"current":
  "arg": [['RobotHardware0_servoState']]
  "func": ['lambda x, idx, mabiki, urata_len=13: x[0][:, (urata_len+1) * idx + (1+1)][::mabiki]']
  "field": [[0,1,2,3,4,5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28]]
  # "field": [[0,1,2,3,4,5], [6,7,8,9,10,11], [12,13,14,15,16], [17, 18, 19, 20, 21, 22, 23, 24], [25, 26, 27, 28, 29, 30, 31, 32]]

"temperature":
  "arg": [['RobotHardware0_servoState'], ['RobotHardware0_servoState']]
  "func": ['lambda x, idx, mabiki, urata_len=13: x[0][:, (urata_len+1) * idx + (0+1)][::mabiki]', 'lambda x, idx, mabiki, urata_len=13: x[0][:, (urata_len+1) * idx + (7+1)][::mabiki]']
  "name": ['motor_temp','motor_outer_tmp']
  "field": [[0,1,2,3,4,5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28]]
  # "field": [[0,1,2,3,4,5], [6,7,8,9,10,11], [12,13,14,15,16], [17, 18, 19, 20, 21, 22, 23, 24], [25, 26, 27, 28, 29, 30, 31, 32]]

"comp":
  "arg": [['st_allEEComp']]
  "post-process": ["self.col_idx % 6 < 3 and self.plot_item.setYRange(-0.025, +0.025) or self.plot_item.setYRange(math.radians(-10), math.radians(+10))"]
  "field": [[0,1,2, 3, 4, 5], [6, 7, 8, 9, 10, 11], [12, 13, 14, 15, 16, 17], [18, 19, 20, 21, 22, 23]]
